# if permissions are not enabled
# everyone can use this marvelous plugin
usePermissions: false

# localized global strings
msg:
  forbidden: Sorry, you have no permission to use this command
  onlyPlayers: Sorry, only for online players for now
  insideGolemSpawn: Inside Golem Spawn Area
  notInVillage: You are not inside a Village radius
  yourRep: Your Reputation
  breedStatus: Breeding Status
  center: Center
  radius: Radius
  villagers: Villagers
  golems: Golems
  houses: Houses
  ok: OK
  stopped: Stopped
