name: VillageInfo
main: cl.netgamer.villageinfo.VI
version: 2

commands:
   villageinfo:
      description: show info about current town.
      usage: "just type '/villageinfo' or '/vi' when inside a town to display info"
      #permission: <plugin name>.basic
      #permission-message: You don't have <permission>
      aliases: [vi,towninfo]

# aqui tambien se configuran los permisos
# no usar la letra enye
