name: VillageInfo
main: cl.netgamer.villageinfo.VI
version: 3

commands:
   villageinfo:
      description: show info about current town.
      usage: "just type '/villageinfo' or '/vi' when inside a town to display info"
      aliases: [vi,towninfo]

# aqui tambien se configuran los permisos (ya no?)
# no usar la letra enye
